services:
  - type: web
    name: gestion-stock-api
    runtime: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: gunicorn config.wsgi:application
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: ALLOWED_HOSTS
        value: gestion-stock-api.onrender.com
      - key: DATABASE_URL
        fromDatabase:
          name: gestion-stock-db
          property: connectionString

databases:
  - name: gestion-stock-db
    databaseName: gestion_stock
    user: gestion_stock_user
